services:
  new-api:
    image: calciumion/new-api:latest
    container_name: new-api
    restart: unless-stopped
    mem_limit: 512m
    cpus: "0.5"
    ports:
      - "3020:3000"
    environment:
      - TZ=Asia/Makassar
      - SESSION_SECRET=ganti_dengan_random_string_panjang
      - SQL_DSN=              # kosongkan = pakai SQLite
      - INITIAL_ROOT_TOKEN=   # opsional: set root token awal
    volumes:
      - /Users/bip/Docker/volumes/new-api:/data          # SQLite + log tersimpan di sini
    networks:
      - public-net

networks:
  public-net:
    external: true